/**
 * This file was generated by ALProxyGenerator
 */

#ifndef ALLAUNCHERPROXY_H_
# define ALLAUNCHERPROXY_H_
# include "alproxy.h"
# include "allauncherproxyposthandler.h"

namespace AL
{
  /**
   * ALLauncherProxy gives acces to all bound methods of the module.
   */
  class ALLauncherProxy : public ALProxy
    {
       public:

       /**
        * Local Constructor
        */
       ALLauncherProxy(ALPtr<ALBroker> pBroker) : ALProxy(pBroker, "ALLauncher")
       { post.setParent( (ALProxy*)this );}

       /**
        * Remote Constructor
        */
       ALLauncherProxy(std::string pIP, int pPort) : ALProxy("ALLauncher", pIP, pPort)
       { post.setParent( (ALProxy*)this );}

       /**
        * \brief: Implements thread wrappers around methods
       */
       ALLauncherProxyPostHandler post;

       /**
        * \brief dataChanged : Called by ALMemory when subscribed data has been modified.
        * \param dataName Name of the modified data
        * \param value value of the data
        * \param message associate message.
        */
       void dataChanged ( std::string dataName, ALValue value, std::string message )
       {
         callVoid( "dataChanged", dataName, value, message );
       }

       /**
        * \brief exit : Exit and unregister module, with no params and no return value.
        */
       void exit (  )
       {
         callVoid( "exit" );
       }

       /**
        * \brief getBrokerName : return the broker name
        * \return broker name : string that contain broker name
        */
       std::string getBrokerName (  )
       {
         return call<std::string>( "getBrokerName" );
       }

       /**
        * \brief getGlobalModuleList : get the list of modules loaded on the robot and connected on the robot
        * \return array : array of present modules
        */
       std::vector<std::string>  getGlobalModuleList (  )
       {
         return call<std::vector<std::string> >( "getGlobalModuleList" );
       }

       /**
        * \brief getMethodHelp : Retrieve a method's description
        * \param methodName the name of the method
        * \return getMethodHelp : a structure containing the method description
        */
       ALValue getMethodHelp ( std::string methodName )
       {
         return call<ALValue>( "getMethodHelp", methodName );
       }

       /**
        * \brief getMethodList : Retrieve the module's method list.
        * \return methodList : an array containing methods name.
        */
       std::vector<std::string>  getMethodList (  )
       {
         return call<std::vector<std::string> >( "getMethodList" );
       }

       /**
        * \brief innerTest : Run an internal test to this module.
        * \return Test_return : true if internal tests are ok
        */
       bool innerTest (  )
       {
         return call<bool>( "innerTest" );
       }

       /**
        * \brief isModulePresent : Tests the existence of an active module in the global system (in same executable or in another executable of the distributed system)
        * \param strPartOfModuleName a part of the name of the module to test existence
        * \return bool : the returned value is true if this module is present
        */
       bool isModulePresent ( std::string strPartOfModuleName )
       {
         return call<bool>( "isModulePresent", strPartOfModuleName );
       }

       /**
        * \brief isRunning : return true if method is currently running
        * \param ID ID of the method to wait
        * \return isRunning : True method is currently running
        */
       bool isRunning ( int ID )
       {
         return call<bool>( "isRunning", ID );
       }

       /**
        * \brief launchExecutable : runs an executable and connect it to current broker (executable)
        * \param moduleName the name of the modulePack to launch or the name of the script file to execute
        * \return bool : true if ok
        */
       bool launchExecutable ( std::string moduleName )
       {
         return call<bool>( "launchExecutable", moduleName );
       }

       /**
        * \brief launchLocal : Loads dynamicaly a module
        * \param moduleName the name of the modulePack to launch or the name of the python script to evaluate
        * \return bool : true if ok
        */
       bool launchLocal ( std::string moduleName )
       {
         return call<bool>( "launchLocal", moduleName );
       }

       /**
        * \brief launchPythonModule : Import a python module
        * \param moduleName the name of the module to launch
        * \return bool : true if ok
        */
       bool launchPythonModule ( std::string moduleName )
       {
         return call<bool>( "launchPythonModule", moduleName );
       }

       /**
        * \brief launchScript : runs a script connected the current broker
        * \param moduleName the name of the script to launch (python or ruby)
        * \return bool : true if ok
        */
       bool launchScript ( std::string moduleName )
       {
         return call<bool>( "launchScript", moduleName );
       }

       /**
        * \brief moduleHelp : Retrieve the module's description
        * \return moduleHelp : a structure describing the module
        */
       ALValue moduleHelp (  )
       {
         return call<ALValue>( "moduleHelp" );
       }

       /**
        * \brief ping : Just a ping, with no params and returning always true
        * \return alwaysTrue : returns always true
        */
       bool ping (  )
       {
         return call<bool>( "ping" );
       }

       /**
        * \brief version : Returns the revision of the module.
        * \return version_string : the string containing the version
        */
       std::string version (  )
       {
         return call<std::string>( "version" );
       }

       /**
        * \brief wait : wait end of execution method if method was called with pCall
        * \param ID ID of the method to wait
        * \param timeout timeout of the wait in ms. 0 if no timeout
        * \return timeout : True if wait exit with timeout
        */
       bool wait ( int ID, int timeout )
       {
         return call<bool>( "wait", ID, timeout );
       }

       /**
        * \brief waitMethod : wait end of execution method if method was called with pCall
        * \param name name of the method to wait
        * \param timeout timeout of the wait. 0 if no timeout
        * \return timeout : True if wait exit with timeout
        */
       int waitMethod ( std::string name, int timeout )
       {
         return call<int>( "waitMethod", name, timeout );
       }

    };
};

#endif
