/**
 * This file was generated by ALProxyGenerator
 */

#ifndef ALSPEECHRECOGNITIONPROXY_H_
# define ALSPEECHRECOGNITIONPROXY_H_
# include "alproxy.h"
# include "alspeechrecognitionproxyposthandler.h"

namespace AL
{
  /**
   * ALSpeechRecognitionProxy gives acces to all bound methods of the module.
   */
  class ALSpeechRecognitionProxy : public ALProxy
    {
       public:

       /**
        * Local Constructor
        */
       ALSpeechRecognitionProxy(ALPtr<ALBroker> pBroker) : ALProxy(pBroker, "ALSpeechRecognition")
       { post.setParent( (ALProxy*)this );}

       /**
        * Remote Constructor
        */
       ALSpeechRecognitionProxy(std::string pIP, int pPort) : ALProxy("ALSpeechRecognition", pIP, pPort)
       { post.setParent( (ALProxy*)this );}

       /**
        * \brief: Implements thread wrappers around methods
       */
       ALSpeechRecognitionProxyPostHandler post;

       /**
        * \brief dataChanged : Called by ALMemory when subscribed data has been modified.
        * \param dataName Name of the modified data
        * \param value value of the data
        * \param message associate message.
        */
       void dataChanged ( std::string dataName, ALValue value, std::string message )
       {
         callVoid( "dataChanged", dataName, value, message );
       }

       /**
        * \brief exit : Exit and unregister module, with no params and no return value.
        */
       void exit (  )
       {
         callVoid( "exit" );
       }

       /**
        * \brief getArrayParam : Gets a parameter that is shaped as an array.This method is intended to be used by advanced users
        * \param pParamName Name of the parameter.
        * \return pParamArrayValue : Value array.
        */
       ALValue getArrayParam ( std::string pParamName )
       {
         return call<ALValue>( "getArrayParam", pParamName );
       }

       /**
        * \brief getAvailableLanguages : Returns the list of the languages installed on the system.
        * \return pLanguagesList : Array of strings containing the list of the installed languages.
        */
       std::vector<std::string>  getAvailableLanguages (  )
       {
         return call<std::vector<std::string> >( "getAvailableLanguages" );
       }

       /**
        * \brief getBrokerName : return the broker name
        * \return broker name : string that contain broker name
        */
       std::string getBrokerName (  )
       {
         return call<std::string>( "getBrokerName" );
       }

       /**
        * \brief getCurrentPeriod : gets the parameters chosen by the Extractor 
        * \return period : refresh period (in millisecond)
        */
       int getCurrentPeriod (  )
       {
         return call<int>( "getCurrentPeriod" );
       }

       /**
        * \brief getCurrentPrecision : gets the parameters chosen by the Extractor 
        * \return precision : precision of the extractor
        */
       float getCurrentPrecision (  )
       {
         return call<float>( "getCurrentPrecision" );
       }

       /**
        * \brief getLanguage : Returns the current language of the speech recognition system.
        * \return pLanguageName : Current language of the speech recognition system.
        */
       std::string getLanguage (  )
       {
         return call<std::string>( "getLanguage" );
       }

       /**
        * \brief getMethodHelp : Retrieve a method's description
        * \param methodName the name of the method
        * \return getMethodHelp : a structure containing the method description
        */
       ALValue getMethodHelp ( std::string methodName )
       {
         return call<ALValue>( "getMethodHelp", methodName );
       }

       /**
        * \brief getMethodList : Retrieve the module's method list.
        * \return methodList : an array containing methods name.
        */
       std::vector<std::string>  getMethodList (  )
       {
         return call<std::vector<std::string> >( "getMethodList" );
       }

       /**
        * \brief getMyPeriod :  gets the parameters given by the module 
        * \param name name of the module which has subscribed
        * \return period : refresh period (in millisecond)
        */
       int getMyPeriod ( std::string name )
       {
         return call<int>( "getMyPeriod", name );
       }

       /**
        * \brief getMyPrecision :  gets the parameters given by the module 
        * \param name name of the module which has subscribed
        * \return precision : precision of the extractor
        */
       float getMyPrecision ( std::string name )
       {
         return call<float>( "getMyPrecision", name );
       }

       /**
        * \brief getOutputNames : get the list of values updated in ALMemory
        * \return outputNames : array of values updated by this extractor in ALMemory
        */
       std::vector<std::string>  getOutputNames (  )
       {
         return call<std::vector<std::string> >( "getOutputNames" );
       }

       /**
        * \brief getParam : Gets a parameter of the speech recognition engine (Ear speech recognition).
        * \param pParamName Name of the parameter.
        * \return pParamValue : Value of the parameter.
        */
       float getParam ( std::string pParamName )
       {
         return call<float>( "getParam", pParamName );
       }

       /**
        * \brief getSubscribersInfo :  gets the parameters given by the module 
        * \return subscribers' info : array of names and parameters of all subscribers.
        */
       ALValue getSubscribersInfo (  )
       {
         return call<ALValue>( "getSubscribersInfo" );
       }

       /**
        * \brief ignoreAllAudioIn : pause all sound aquisition (to stop while speeh synthetising or ...)
        * \param bSetOrUnset enable the functionnality when true.
        */
       void ignoreAllAudioIn ( bool bSetOrUnset )
       {
         callVoid( "ignoreAllAudioIn", bSetOrUnset );
       }

       /**
        * \brief innerTest : Run an internal test to this module.
        * \return Test_return : true if internal tests are ok
        */
       bool innerTest (  )
       {
         return call<bool>( "innerTest" );
       }

       /**
        * \brief isRunning : return true if method is currently running
        * \param ID ID of the method to wait
        * \return isRunning : True method is currently running
        */
       bool isRunning ( int ID )
       {
         return call<bool>( "isRunning", ID );
       }

       /**
        * \brief moduleHelp : Retrieve the module's description
        * \return moduleHelp : a structure describing the module
        */
       ALValue moduleHelp (  )
       {
         return call<ALValue>( "moduleHelp" );
       }

       /**
        * \brief ping : Just a ping, with no params and returning always true
        * \return alwaysTrue : returns always true
        */
       bool ping (  )
       {
         return call<bool>( "ping" );
       }

       /**
        * \brief setArrayParam : Sets a parameter that is shaped as an array. This method is intended to be used by advanced users
        * \param pParamName Name of the parameter.
        * \param pParamArrayValue Value array.
        */
       void setArrayParam ( std::string pParamName, ALValue pParamArrayValue )
       {
         callVoid( "setArrayParam", pParamName, pParamArrayValue );
       }

       /**
        * \brief setDebugMode : enable/disable the printing of some debug information
        * \param bSetOrUnset enable the functionnality when true.
        */
       void setDebugMode ( bool bSetOrUnset )
       {
         callVoid( "setDebugMode", bSetOrUnset );
       }

       /**
        * \brief setLanguage : Sets the language of the speech recognition.  The list of the available languages can be get with the getAvailableLanguages method.
        * \param pLanguage Language string. 2 language(s) currently available(s) on the system : English French 
        */
       void setLanguage ( std::string pLanguage )
       {
         callVoid( "setLanguage", pLanguage );
       }

       /**
        * \brief setOutputToFile : enable/disable output of all audioin to file. (direct call AudioInManager::setOutputToFile)
        * \param bSetOrUnset enable the functionnality when true.
        */
       void setOutputToFile ( bool bSetOrUnset )
       {
         callVoid( "setOutputToFile", bSetOrUnset );
       }

       /**
        * \brief setParam : Sets a parameter of the speech recognition engine.		The parameters that can be set and the corresponding values are :
	       # EarUseSpeechDetector - Values : 0 (No), 1 (Regular), or 2 (Cepstral) - tells to the recognition system to not recognize frames that seem to be silence	       # EarNoiseReduction - Values : 0 (no) or 1 (yes) - Applies noise reduction to the signal. It's often a good idea to use it, but be warned, it sometimes causes problems to Speech Detection when used in conjunction with the Cepstral Speech Detector.	       # EarSpeed - Values : 0 to 3 - 0 is slowest and most accurate. 3 is the fastest but may add some recognition errors, especially if you talk fast because some parts of the audio data is not processed. - suggested value is 2	       # EarUseFilter : Values : 0 (no) or 1 (yes) - Applies a High-Pass filter on the input signal
        * \param pParamName Name of the parameter.
        * \param pParamValue Value of the parameter.
        */
       void setParam ( std::string pParamName, float pParamValue )
       {
         callVoid( "setParam", pParamName, pParamValue );
       }

       /**
        * \brief setVisualExpression : Enables the leds feedback showing the nao state.
        * \param bSetOrNot Enable or disable it.
        */
       void setVisualExpression ( bool bSetOrNot )
       {
         callVoid( "setVisualExpression", bSetOrNot );
       }

       /**
        * \brief setWordListAsVocabulary : Sets an array of strings as vocabulary.
        * \param pVocabulary List of words to recognize
        */
       void setWordListAsVocabulary ( std::vector<std::string>  pVocabulary )
       {
         callVoid( "setWordListAsVocabulary", pVocabulary );
       }

       /**
        * \brief startDetection : Start the peak detection.
        */
       void startDetection (  )
       {
         callVoid( "startDetection" );
       }

       /**
        * \brief stopDetection : Stop the peak detection.
        */
       void stopDetection (  )
       {
         callVoid( "stopDetection" );
       }

       /**
        * \brief subscribe :  subscribes to the extractor 
        * \param name name of the module which subscribes
        * \param period refresh period (in millisecond)
        * \param precision precision of the extractor
        */
       void subscribe ( std::string name, int period, float precision )
       {
         callVoid( "subscribe", name, period, precision );
       }

       /**
        * \brief unsubscribe :  unsubscribes to the extractor 
        * \param name name of the module which has subscribed
        */
       void unsubscribe ( std::string name )
       {
         callVoid( "unsubscribe", name );
       }

       /**
        * \brief updatePeriod :  updates the parameters 
        * \param name name of the module which has subscribed
        * \param period refresh period (in millisecond)
        */
       void updatePeriod ( std::string name, int period )
       {
         callVoid( "updatePeriod", name, period );
       }

       /**
        * \brief updatePrecision :  updates the parameters 
        * \param name name of the module which has subscribed
        * \param precision precision of the extractor
        */
       void updatePrecision ( std::string name, float precision )
       {
         callVoid( "updatePrecision", name, precision );
       }

       /**
        * \brief version : Returns the revision of the module.
        * \return version_string : the string containing the version
        */
       std::string version (  )
       {
         return call<std::string>( "version" );
       }

       /**
        * \brief wait : wait end of execution method if method was called with pCall
        * \param ID ID of the method to wait
        * \param timeout timeout of the wait in ms. 0 if no timeout
        * \return timeout : True if wait exit with timeout
        */
       bool wait ( int ID, int timeout )
       {
         return call<bool>( "wait", ID, timeout );
       }

       /**
        * \brief waitMethod : wait end of execution method if method was called with pCall
        * \param name name of the method to wait
        * \param timeout timeout of the wait. 0 if no timeout
        * \return timeout : True if wait exit with timeout
        */
       int waitMethod ( std::string name, int timeout )
       {
         return call<int>( "waitMethod", name, timeout );
       }

    };
};

#endif
