#!/bin/sh

IP1=$(ifconfig eth0 |grep "inet addr:" |sed 's/^.*addr:\([0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+\).*$/\1/')
IP2=$(ifconfig wlan0 |grep "inet addr:" |sed 's/^.*addr:\([0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+\).*$/\1/')

#no eth0, we use eth1
if [ x$IP1 != x ] ; then
  IP=$IP1
else
  IP=$IP2
fi

export AL_DIR="/opt/naoqi"
export GT_DIR="/media/userdata"
export SUPPRESS_IP="yes"
export LD_LIBRARY_PATH="$AL_DIR/lib/linux"
export URBI_PATH="$AL_DIR/bin"
export PATH=${AL_DIR}/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

export IP

cd /opt/naoqi
bin/naoqi -b $IP 
