#!/bin/sh

if [ -n  "$(ps | egrep [n]ao)" ]; then
	echo NaoQi is running
else
	echo NaoQi is not running
fi

if [ -n  "$(ps | egrep [b]hu)" ]; then
        echo bhuman is running
else
        echo bhuman is not running
fi

