#
# DO NOT MODIFY!!!!
# This file is automatically generated by racc 1.4.4
# from racc grammer file "xabsl_parser.y.rb".
#

require 'racc/parser'



require 'translator'
require 'syntax_tree_builder'


module Translator

  class XabslParser < Racc::Parser

module_eval <<'..end xabsl_parser.y.rb modeval..id866165210a', 'xabsl_parser.y.rb', 548

def initialize
	super
end

#start the parsing, use stb as SyntaxTreeBuilder, tokenize and rewind on demand
def parse(cc, stb)
	@cc = cc
	@stb = stb
	@stb.compiler_context = cc
    if @cc.tz.tokenized?	
    	@cc.tz.rewind
    else
    	File.open(cc.cu.src_fullname, 'rb') do |src|
            @cc.tz.tokenize(src.read)
		end
    end
	do_parse
	@cc = nil
	@stb.compiler_context = nil
	@stb = nil
end

#return a token in the format the parser understands
def next_token
	token = @cc.tz.next_token
	return nil if token.nil?
	return [token.token_type, token]
end

def on_error(error_token_id, error_value, value_stack)
	if error_value == '$'
		raise UnexpectedEndOfFile.new(@cc)
	else
		error = SyntaxError.new(@cc)
		error.token = error_value if error_value.class <= Token
		raise error
	end
end

..end xabsl_parser.y.rb modeval..id866165210a

##### racc 1.4.4 generates ###

racc_reduce_table = [
 0, 0, :racc_error,
 2, 67, :_reduce_1,
 1, 68, :_reduce_none,
 0, 68, :_reduce_none,
 2, 69, :_reduce_none,
 1, 69, :_reduce_none,
 1, 69, :_reduce_none,
 1, 69, :_reduce_none,
 0, 69, :_reduce_none,
 2, 72, :_reduce_none,
 1, 72, :_reduce_none,
 3, 70, :_reduce_11,
 0, 77, :_reduce_12,
 10, 73, :_reduce_13,
 2, 76, :_reduce_14,
 2, 76, :_reduce_15,
 2, 76, :_reduce_16,
 2, 76, :_reduce_17,
 0, 76, :_reduce_18,
 0, 83, :_reduce_19,
 7, 81, :_reduce_20,
 0, 89, :_reduce_21,
 9, 79, :_reduce_22,
 1, 85, :_reduce_none,
 1, 85, :_reduce_none,
 1, 85, :_reduce_none,
 0, 85, :_reduce_none,
 7, 80, :_reduce_27,
 2, 90, :_reduce_28,
 3, 91, :_reduce_29,
 0, 91, :_reduce_30,
 1, 92, :_reduce_none,
 0, 92, :_reduce_none,
 1, 84, :_reduce_none,
 1, 84, :_reduce_none,
 2, 84, :_reduce_35,
 0, 84, :_reduce_none,
 9, 78, :_reduce_37,
 1, 93, :_reduce_none,
 0, 93, :_reduce_none,
 9, 74, :_reduce_40,
 0, 96, :_reduce_41,
 9, 71, :_reduce_42,
 3, 88, :_reduce_43,
 0, 88, :_reduce_none,
 2, 82, :_reduce_45,
 0, 82, :_reduce_46,
 6, 97, :_reduce_47,
 1, 86, :_reduce_none,
 0, 86, :_reduce_none,
 1, 87, :_reduce_none,
 0, 87, :_reduce_none,
 2, 95, :_reduce_52,
 2, 99, :_reduce_53,
 0, 99, :_reduce_54,
 0, 104, :_reduce_55,
 12, 98, :_reduce_56,
 2, 103, :_reduce_57,
 2, 103, :_reduce_58,
 0, 103, :_reduce_59,
 0, 108, :_reduce_60,
 5, 105, :_reduce_61,
 1, 75, :_reduce_none,
 0, 75, :_reduce_none,
 1, 100, :_reduce_none,
 0, 100, :_reduce_none,
 1, 101, :_reduce_none,
 0, 101, :_reduce_none,
 0, 111, :_reduce_68,
 7, 106, :_reduce_69,
 1, 109, :_reduce_none,
 1, 109, :_reduce_none,
 0, 109, :_reduce_none,
 2, 110, :_reduce_73,
 0, 110, :_reduce_74,
 2, 113, :_reduce_75,
 0, 113, :_reduce_76,
 0, 114, :_reduce_77,
 4, 112, :_reduce_78,
 2, 115, :_reduce_79,
 0, 115, :_reduce_80,
 2, 117, :_reduce_81,
 0, 117, :_reduce_82,
 0, 118, :_reduce_83,
 4, 116, :_reduce_84,
 2, 107, :_reduce_85,
 0, 120, :_reduce_86,
 4, 107, :_reduce_87,
 0, 121, :_reduce_88,
 4, 107, :_reduce_89,
 0, 122, :_reduce_90,
 4, 107, :_reduce_91,
 0, 123, :_reduce_92,
 4, 107, :_reduce_93,
 0, 124, :_reduce_94,
 4, 107, :_reduce_95,
 0, 125, :_reduce_96,
 4, 107, :_reduce_97,
 0, 126, :_reduce_98,
 4, 107, :_reduce_99,
 0, 127, :_reduce_100,
 4, 107, :_reduce_101,
 0, 128, :_reduce_102,
 4, 107, :_reduce_103,
 0, 129, :_reduce_104,
 4, 107, :_reduce_105,
 0, 130, :_reduce_106,
 4, 107, :_reduce_107,
 0, 131, :_reduce_108,
 4, 107, :_reduce_109,
 0, 132, :_reduce_110,
 4, 107, :_reduce_111,
 5, 107, :_reduce_112,
 3, 107, :_reduce_113,
 2, 107, :_reduce_114,
 1, 107, :_reduce_115,
 1, 107, :_reduce_116,
 1, 107, :_reduce_117,
 1, 107, :_reduce_none,
 1, 107, :_reduce_119,
 1, 107, :_reduce_120,
 1, 107, :_reduce_121,
 1, 107, :_reduce_122,
 0, 133, :_reduce_123,
 5, 119, :_reduce_124,
 6, 94, :_reduce_125,
 3, 94, :_reduce_126,
 3, 94, :_reduce_127,
 0, 94, :_reduce_none,
 3, 135, :_reduce_129,
 0, 135, :_reduce_none,
 3, 134, :_reduce_131,
 0, 134, :_reduce_none,
 3, 136, :_reduce_133,
 7, 136, :_reduce_134,
 3, 138, :_reduce_135,
 0, 138, :_reduce_136,
 4, 102, :_reduce_137,
 6, 102, :_reduce_138,
 0, 102, :_reduce_139,
 3, 137, :_reduce_140,
 1, 137, :_reduce_141,
 9, 137, :_reduce_142,
 3, 139, :_reduce_143,
 2, 139, :_reduce_144 ]

racc_reduce_n = 145

racc_shift_n = 264

racc_action_table = [
   143,   145,   147,   148,   149,   150,   151,   137,   138,   139,
   141,   142,   144,   146,   115,    -8,    -8,   115,     7,   120,
     7,    48,   120,   233,    49,    50,    82,   130,     7,   209,
   228,   123,   124,   113,   123,   124,   113,   116,     7,   105,
   116,   115,     7,     7,    82,   -63,   120,   127,    68,   259,
   117,   118,   119,   117,   118,   119,   245,   159,   123,   124,
   113,   106,   107,   152,   116,   154,    72,    75,   114,    13,
    13,   114,     7,     7,    81,   157,   126,   117,   118,   119,
   143,   145,   147,   148,   149,   150,   151,   137,   138,   139,
   141,   142,   144,   146,   115,   114,     7,     7,     7,   120,
     7,   225,  -136,   168,   170,    96,   168,   170,     7,   158,
   128,   123,   124,   113,   168,   170,     7,   116,   162,   125,
    19,   164,   168,   170,    68,   169,    68,    44,   169,    97,
   117,   118,   119,   -72,   140,    18,   169,   112,   111,     7,
   186,   -52,   187,    20,   169,   168,   170,    89,   114,   143,
   145,   147,   148,   149,   150,   151,   137,   138,   139,   141,
   142,   144,   146,   115,   191,   109,    46,   169,   120,   194,
   115,   196,   198,   115,   -38,   120,   104,     7,   120,    47,
   123,   124,   113,   168,   170,   103,   116,   123,   124,   113,
   123,   124,   113,   116,   204,    58,   116,   115,   206,   117,
   118,   119,   120,   258,   101,   169,   117,   118,   119,   117,
   118,   119,   209,   100,   123,   124,   113,   114,    48,    95,
   116,    49,    92,   -39,   114,    94,    89,   114,   143,   145,
   147,    88,    87,   117,   118,   119,   143,   145,   147,   148,
   149,   150,   151,   137,   138,   139,   141,   142,   144,   146,
   115,   114,   143,   145,   147,   120,    86,   115,    80,    72,
   115,    71,   120,    65,    63,   120,   221,   123,   124,   113,
   222,   223,    62,   116,   123,   124,   113,   123,   124,   113,
   116,   227,    60,   116,   115,   229,   117,   118,   119,   120,
   163,   162,   231,   117,   118,   119,   117,   118,   119,  -123,
   234,   123,   124,   113,   114,    58,    56,   116,   115,    55,
   236,   114,   237,   120,   114,   238,   239,    53,   115,    44,
   117,   118,   119,   120,    41,   123,   124,   113,    40,    35,
    34,   116,    32,    31,    89,   123,   124,   113,   114,   242,
   244,   116,   115,    29,   117,   118,   119,   120,    28,    27,
   248,   198,   115,    26,   117,   118,   119,   120,    25,   123,
   124,   113,   114,    24,   252,   116,   253,   255,   256,   123,
   124,   113,   114,    23,    22,   116,   115,    18,   117,   118,
   119,   120,    21,    14,     4,     7,   115,   262,   117,   118,
   119,   120,     3,   123,   124,   113,   114,   nil,   nil,   116,
   nil,   nil,   nil,   123,   124,   113,   114,   nil,   nil,   116,
   115,   nil,   117,   118,   119,   120,   nil,   nil,   nil,   nil,
   115,   nil,   117,   118,   119,   120,   nil,   123,   124,   113,
   114,   nil,   nil,   116,   nil,   nil,   nil,   123,   124,   113,
   114,   nil,   nil,   116,   115,   nil,   117,   118,   119,   120,
   nil,   nil,   nil,   nil,   115,   nil,   117,   118,   119,   120,
   nil,   123,   124,   113,   114,   nil,   nil,   116,   nil,   nil,
   nil,   123,   124,   113,   114,   nil,   nil,   116,   115,   nil,
   117,   118,   119,   120,     7,   nil,   nil,  -128,    37,   nil,
   117,   118,   119,   nil,   nil,   123,   124,   113,   114,  -128,
  -128,   116,   nil,   nil,   nil,   nil,   nil,   nil,   114,   nil,
   nil,   nil,   nil,   nil,   117,   118,   119,   143,   145,   147,
   148,   149,   150,   151,   137,   138,   139,   141,   142,   144,
   146,   215,   114,   143,   145,   147,   148,   149,   150,   151,
   137,   138,   139,   141,   142,   144,   146,   143,   145,   147,
   148,   149,   150,   151,   137,   138,   139,   141,   142,   144,
  -145,   143,   145,   147,   148,   149,   150,   151,   137,   138,
   139,   141,   142,   144,   146,   143,   145,   147,   148,   149,
   150,   151,   137,   138,   139,   141,   142,   143,   145,   147,
   148,   149,  -145,  -145,  -145,  -145,  -145,  -145,   143,   145,
   147,   148,   149,  -145,  -145,  -145,  -145,  -145,  -145,   143,
   145,   147,   148,   149,  -145,  -145,  -145,  -145,  -145,  -145,
   143,   145,   147,   148,   149,   150,   151,   137,   138,   139,
   141,   143,   145,   147,   148,   149,  -145,  -145,  -145,  -145,
  -145,  -145,   143,   145,   147,   148,   149,  -145,  -145,  -145,
  -145,  -145,  -145,   143,   145,   147,   148,   149,  -145,  -145,
  -145,  -145,  -145,  -145 ]

racc_action_check = [
   131,   131,   131,   131,   131,   131,   131,   131,   131,   131,
   131,   131,   131,   131,   231,     2,     6,   114,   254,   231,
    60,    38,   114,   199,    38,    38,   226,   110,    11,   193,
   193,   231,   231,   231,   114,   114,   114,   231,    64,    93,
   114,   111,     2,     6,    67,    11,   111,   108,    60,   254,
   231,   231,   231,   114,   114,   114,   226,   131,   111,   111,
   111,    93,    93,   125,   111,   126,   127,    64,   231,     2,
     6,   114,   190,   171,    67,   129,   108,   111,   111,   111,
   121,   121,   121,   121,   121,   121,   121,   121,   121,   121,
   121,   121,   121,   121,   183,   111,   238,   262,    68,   183,
   258,   190,   171,   262,   262,    82,   258,   258,   228,   130,
   109,   183,   183,   183,   228,   228,   140,   183,   132,   104,
    12,   135,   140,   140,   238,   262,    68,    57,   258,    82,
   183,   183,   183,    82,   121,    12,   228,    99,    98,   158,
   152,    57,   153,    12,   140,   158,   158,   155,   183,   251,
   251,   251,   251,   251,   251,   251,   251,   251,   251,   251,
   251,   251,   251,   248,   157,    94,    37,   158,   248,   160,
   120,   161,   164,   184,    92,   120,    91,   169,   184,    37,
   248,   248,   248,   169,   169,    90,   248,   120,   120,   120,
   184,   184,   184,   120,   168,    88,   184,   239,   170,   248,
   248,   248,   239,   251,    87,   169,   120,   120,   120,   184,
   184,   184,   173,    85,   239,   239,   239,   248,    79,    80,
   239,    79,    79,    79,   120,    79,    73,   184,   217,   217,
   217,    71,    70,   239,   239,   239,   133,   133,   133,   133,
   133,   133,   133,   133,   133,   133,   133,   133,   133,   133,
   115,   239,   218,   218,   218,   115,    69,   101,    65,    63,
   181,    61,   101,    54,    51,   181,   185,   115,   115,   115,
   187,   188,    48,   115,   101,   101,   101,   181,   181,   181,
   101,   192,    47,   181,   180,   194,   115,   115,   115,   180,
   133,   196,   197,   101,   101,   101,   181,   181,   181,   116,
   200,   180,   180,   180,   115,    46,    43,   180,   165,    42,
   204,   101,   205,   165,   181,   208,   209,    41,   166,    36,
   180,   180,   180,   166,    35,   165,   165,   165,    34,    32,
    31,   165,    29,    28,   221,   166,   166,   166,   180,   223,
   224,   166,   167,    26,   165,   165,   165,   167,    24,    23,
   232,   234,   182,    22,   166,   166,   166,   182,    21,   167,
   167,   167,   165,    20,   241,   167,   243,   245,   246,   182,
   182,   182,   166,    19,    18,   182,   215,    17,   167,   167,
   167,   215,    13,     4,     1,   260,   174,   261,   182,   182,
   182,   174,     0,   215,   215,   215,   167,   nil,   nil,   215,
   nil,   nil,   nil,   174,   174,   174,   182,   nil,   nil,   174,
   175,   nil,   215,   215,   215,   175,   nil,   nil,   nil,   nil,
   176,   nil,   174,   174,   174,   176,   nil,   175,   175,   175,
   215,   nil,   nil,   175,   nil,   nil,   nil,   176,   176,   176,
   174,   nil,   nil,   176,   177,   nil,   175,   175,   175,   177,
   nil,   nil,   nil,   nil,   178,   nil,   176,   176,   176,   178,
   nil,   177,   177,   177,   175,   nil,   nil,   177,   nil,   nil,
   nil,   178,   178,   178,   176,   nil,   nil,   178,   146,   nil,
   177,   177,   177,   146,    33,   nil,   nil,    33,    33,   nil,
   178,   178,   178,   nil,   nil,   146,   146,   146,   177,    33,
    33,   146,   nil,   nil,   nil,   nil,   nil,   nil,   178,   nil,
   nil,   nil,   nil,   nil,   146,   146,   146,   179,   179,   179,
   179,   179,   179,   179,   179,   179,   179,   179,   179,   179,
   179,   179,   146,   257,   257,   257,   257,   257,   257,   257,
   257,   257,   257,   257,   257,   257,   257,   240,   240,   240,
   240,   240,   240,   240,   240,   240,   240,   240,   240,   240,
   240,   247,   247,   247,   247,   247,   247,   247,   247,   247,
   247,   247,   247,   247,   247,   213,   213,   213,   213,   213,
   213,   213,   213,   213,   213,   213,   213,   202,   202,   202,
   202,   202,   202,   202,   202,   202,   202,   202,   220,   220,
   220,   220,   220,   220,   220,   220,   220,   220,   220,   203,
   203,   203,   203,   203,   203,   203,   203,   203,   203,   203,
   211,   211,   211,   211,   211,   211,   211,   211,   211,   211,
   211,   201,   201,   201,   201,   201,   201,   201,   201,   201,
   201,   201,   219,   219,   219,   219,   219,   219,   219,   219,
   219,   219,   219,   210,   210,   210,   210,   210,   210,   210,
   210,   210,   210,   210 ]

racc_action_pointer = [
   364,   384,    15,   nil,   383,   nil,    16,   nil,   nil,   nil,
   nil,     1,    91,   359,   nil,   nil,   nil,   333,   348,   347,
   337,   297,   296,   294,   291,   nil,   320,   nil,   310,   272,
   nil,   272,   303,   457,   273,   266,   277,   147,   -25,   nil,
   nil,   256,   266,   250,   nil,   nil,   250,   227,   246,   nil,
   nil,   238,   nil,   nil,   233,   nil,   nil,    85,   nil,   nil,
    -7,   230,   nil,   235,    11,   232,   nil,    18,    71,   200,
   195,   212,   nil,   203,   nil,   nil,   nil,   nil,   nil,   172,
   164,   nil,    76,   nil,   nil,   157,   nil,   147,   140,   nil,
   124,   125,   123,    14,   139,   nil,   nil,   nil,    73,    80,
   nil,   254,   nil,   nil,    93,   nil,   nil,   nil,    21,    55,
    -5,    38,   nil,   nil,    14,   247,   242,   nil,   nil,   nil,
   167,    76,   nil,   nil,   nil,    -2,    39,    42,   nil,    56,
    54,    -4,    92,   232,   nil,    64,   nil,   nil,   nil,   nil,
    89,   nil,   nil,   nil,   nil,   nil,   475,   nil,   nil,   nil,
   nil,   nil,   132,    86,   nil,   124,   nil,   109,   112,   nil,
   111,   111,   nil,   nil,   146,   305,   315,   339,   168,   150,
   137,    46,   nil,   175,   383,   407,   417,   441,   451,   513,
   281,   257,   349,    91,   170,   246,   nil,   209,   211,   nil,
    45,   nil,   225,    -8,   224,   nil,   265,   227,   nil,   -35,
   240,   627,   583,   605,   249,   256,   nil,   nil,   277,   259,
   649,   616,   nil,   571,   nil,   373,   nil,   224,   248,   638,
   594,   311,   nil,   313,   283,   nil,     0,   nil,    81,   nil,
   nil,    11,   285,   nil,   325,   nil,   nil,   nil,    69,   194,
   543,   303,   nil,   305,   nil,   311,   312,   557,   160,   nil,
   nil,   145,   nil,   nil,    -9,   nil,   nil,   529,    73,   nil,
   358,   349,    70,   nil ]

racc_action_default = [
    -3,  -145,   -63,    -2,  -145,    -1,   -63,   -62,    -5,    -6,
    -7,   -10,  -145,  -145,   264,    -4,    -9,  -145,  -145,  -145,
  -145,  -145,  -145,  -145,  -145,   -11,  -145,   -41,  -145,  -145,
   -46,  -145,  -145,   -63,  -145,  -145,   -65,  -145,   -36,   -45,
   -12,  -145,   -67,  -145,   -64,   -54,  -130,  -132,  -145,   -33,
   -34,  -145,   -18,   -40,  -145,   -66,   -42,   -65,   -59,  -127,
   -63,  -126,   -35,   -49,   -63,  -145,   -53,  -145,   -63,  -145,
  -145,  -145,   -48,   -51,   -14,   -13,   -15,   -16,   -17,   -36,
  -145,  -129,   -60,   -57,   -58,  -145,  -131,  -145,  -130,   -50,
  -145,  -145,   -34,   -26,  -145,   -55,   -70,   -71,  -145,  -145,
  -133,  -145,  -125,   -47,  -145,   -25,   -23,   -24,  -145,  -145,
  -139,  -145,   -68,  -117,  -145,  -145,  -119,  -121,  -120,  -122,
  -145,  -145,  -118,  -115,  -116,  -145,  -145,   -49,   -19,  -145,
  -145,  -145,   -74,  -145,   -85,  -145,  -114,  -102,  -106,   -98,
   -63,   -96,  -108,   -90,  -110,   -92,  -145,   -94,   -86,   -88,
  -100,  -104,   -32,  -145,   -30,   -51,   -46,  -145,   -63,   -61,
  -145,   -76,   -77,  -113,   -80,  -145,  -145,  -145,  -145,   -63,
  -145,   -63,  -141,  -145,  -145,  -145,  -145,  -145,  -145,  -145,
  -145,  -145,  -145,  -145,  -145,  -145,   -31,  -145,   -28,   -21,
   -63,   -59,  -145,  -145,  -145,   -73,   -74,  -145,   -83,  -145,
   -82,  -103,  -107,   -99,  -145,  -145,  -144,  -134,  -145,  -145,
   -97,  -109,   -91,  -111,   -93,  -145,   -95,   -87,   -89,  -101,
  -105,   -51,   -27,  -145,   -44,   -20,  -145,  -137,   -63,   -69,
   -75,  -145,  -145,  -124,   -80,   -79,  -143,  -140,   -63,  -145,
  -112,  -145,   -29,  -145,   -46,  -145,  -145,   -78,  -145,   -81,
  -135,  -145,   -37,   -22,   -63,   -56,  -138,   -84,   -63,   -43,
   -63,  -145,   -63,  -142 ]

racc_goto_table = [
    12,    33,    69,    90,    12,    67,   171,   121,   199,    17,
    85,    73,   160,    59,     5,    51,    45,   131,    15,     1,
   133,   134,   108,   156,   192,   243,   136,   224,   153,   188,
   185,    38,    91,    36,    43,   205,    30,    66,    78,    57,
    54,   129,    77,   110,    76,    98,    99,    74,   132,   195,
   197,    52,   179,   235,   232,   102,    93,   181,    70,   182,
   176,   178,    79,   180,   174,   167,    70,   183,   165,   184,
   166,   201,   202,   203,   175,   155,   230,   177,   249,   135,
   210,   211,   212,   213,   214,   189,   216,   217,   218,   219,
   220,    61,    64,    16,   246,     2,   207,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   240,   nil,   nil,   260,   nil,   nil,   190,   263,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   247,   226,   nil,
   nil,   nil,   nil,   nil,   nil,   251,   nil,   nil,   nil,   nil,
   nil,   241,   nil,   nil,   257,   nil,   193,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   208,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   250,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    38,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   254,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    70,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    38,   nil,   nil,   nil,   nil,   nil,   261 ]

racc_goto_check = [
     9,    16,    70,    21,     9,    37,    71,    41,    49,     9,
    70,    20,    44,    69,     3,    18,    32,    41,     3,     1,
    41,    41,    19,    17,    71,    22,    41,    23,    24,    25,
    26,     9,    27,    28,    29,    71,    30,    32,    15,    33,
    35,    36,    14,    38,    13,    42,    43,    12,    45,    47,
    48,    11,    41,    51,    52,    69,    18,    54,     9,    55,
    56,    57,     9,    58,    59,    60,     9,    61,    62,    63,
    64,    41,    41,    41,    65,    20,    44,    66,    49,    67,
    41,    41,    41,    41,    41,    21,    41,    41,    41,    41,
    41,    68,    10,     6,    71,     2,    72,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    41,   nil,   nil,    71,   nil,   nil,    16,    71,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    41,    37,   nil,
   nil,   nil,   nil,   nil,   nil,    41,   nil,   nil,   nil,   nil,
   nil,    21,   nil,   nil,    41,   nil,     9,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     9,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    70,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     9,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    16,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,     9,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,     9,   nil,   nil,   nil,   nil,   nil,     9 ]

racc_goto_pointer = [
   nil,    19,    95,    12,   nil,   nil,    82,   nil,   nil,    -2,
    40,    11,   -17,   -20,   -22,   -26,   -29,  -105,   -23,   -71,
   -52,   -70,  -199,  -162,   -98,  -125,  -122,   -47,     0,    -2,
     9,   nil,   -20,    -6,   nil,    -2,   -69,   -53,   -52,   nil,
   nil,   -94,   -37,   -36,  -120,   -64,   nil,  -112,  -112,  -156,
   nil,  -147,  -144,   nil,   -91,   -90,   -83,   -84,   -84,   -77,
   -74,   -83,   -69,   -82,   -68,   -68,   -67,   -37,    44,   -33,
   -58,  -134,   -75,   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,     6,     8,     9,    10,    11,   173,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    39,   nil,   nil,    42,   nil,   nil,   nil,   nil,    83,
    84,   nil,   nil,   nil,   nil,   nil,   161,   nil,   nil,   nil,
   200,   nil,   nil,   122,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   172 ]

racc_token_table = {
 false => 0,
 Object.new => 1,
 :UMINUS => 2,
 "!" => 3,
 "*" => 4,
 "/" => 5,
 "%" => 6,
 "+" => 7,
 "-" => 8,
 "<" => 9,
 ">" => 10,
 :LE => 11,
 :GE => 12,
 :EQ => 13,
 :NEQ => 14,
 :AND => 15,
 :OR => 16,
 "?" => 17,
 ":" => 18,
 :ACTION => 19,
 :NUMBER => 20,
 :TRUE => 21,
 :FALSE => 22,
 :STRING => 23,
 :RANGE => 24,
 :INTERNAL => 25,
 :IDENTIFIER => 26,
 :DOC_COMMENT => 27,
 :INITIAL_COMMENT => 28,
 :OPTION => 29,
 :STATE => 30,
 :COMMON => 31,
 :DECISION => 32,
 :TTS => 33,
 :STAY => 34,
 :DT => 35,
 :CDT => 36,
 :IF => 37,
 :ELSE => 38,
 :TOOX => 39,
 :TOSX => 40,
 :SORTS => 41,
 :INITIAL => 42,
 :TARGET => 43,
 :AGENT => 44,
 :FUNCTION => 45,
 :ENUM => 46,
 :INPUT => 47,
 :OUTPUT => 48,
 :BOOL => 49,
 :FLOAT => 50,
 :CONST => 51,
 :NAMESPACE => 52,
 :BEHAVIOR => 53,
 :INCLUDE => 54,
 "{" => 55,
 "}" => 56,
 "(" => 57,
 ")" => 58,
 "|" => 59,
 "," => 60,
 ";" => 61,
 "<=" => 62,
 ">=" => 63,
 "==" => 64,
 "=" => 65 }

racc_use_result_var = true

racc_nt_base = 66

Racc_arg = [
 racc_action_table,
 racc_action_check,
 racc_action_default,
 racc_action_pointer,
 racc_goto_table,
 racc_goto_check,
 racc_goto_default,
 racc_goto_pointer,
 racc_nt_base,
 racc_reduce_table,
 racc_token_table,
 racc_shift_n,
 racc_reduce_n,
 racc_use_result_var ]

Racc_token_to_s_table = [
'$end',
'error',
'UMINUS',
'"!"',
'"*"',
'"/"',
'"%"',
'"+"',
'"-"',
'"<"',
'">"',
'LE',
'GE',
'EQ',
'NEQ',
'AND',
'OR',
'"?"',
'":"',
'ACTION',
'NUMBER',
'TRUE',
'FALSE',
'STRING',
'RANGE',
'INTERNAL',
'IDENTIFIER',
'DOC_COMMENT',
'INITIAL_COMMENT',
'OPTION',
'STATE',
'COMMON',
'DECISION',
'TTS',
'STAY',
'DT',
'CDT',
'IF',
'ELSE',
'TOOX',
'TOSX',
'SORTS',
'INITIAL',
'TARGET',
'AGENT',
'FUNCTION',
'ENUM',
'INPUT',
'OUTPUT',
'BOOL',
'FLOAT',
'CONST',
'NAMESPACE',
'BEHAVIOR',
'INCLUDE',
'"{"',
'"}"',
'"("',
'")"',
'"|"',
'","',
'";"',
'"<="',
'">="',
'"=="',
'"="',
'$start',
'xtc',
'__initial_comment',
'__top_level',
'include',
'option',
'agents',
'namespace',
'agent',
'__doc_comment',
'__inner_namespace',
'@1',
'const',
'symbol_declaration',
'enum_symbol_declaration',
'behavior_declaration',
'__parameter_declarations',
'@2',
'bool_or_float_or_enum',
'__input_output_internal',
'__range',
'__measure',
'symbol_parameter_declarations',
'@3',
'enum_elements',
'__enum_elements',
'__minus',
'__float',
'__common_declarations',
'state_declarations',
'@4',
'parameter_declaration',
'state_declaration',
'__state_declarations',
'__initial',
'__target',
'decision_tree',
'__output_symbol_assignments_or_subsequent_declarations',
'@5',
'output_symbol_assignment',
'subsequent_declaration',
'exp',
'@6',
'__option_or_behavior',
'__set_parameter_list',
'@7',
'set_parameter',
'__set_parameter_list_end',
'@8',
'__with_parameter_list',
'with_parameter',
'__with_parameter_list_end',
'@9',
'function',
'@10',
'@11',
'@12',
'@13',
'@14',
'@15',
'@16',
'@17',
'@18',
'@19',
'@20',
'@21',
'@22',
'@23',
'__common_decision_tree',
'__common_action',
'cdtree',
'dtree',
'__cdtree_elseif_decisions',
'transition']

Racc_debug_parser = false

##### racc system variables end #####

 # reduce 0 omitted

module_eval <<'.,.,', 'xabsl_parser.y.rb', 70
  def _reduce_1( val, _values, result )
@stb.comments(val)
   result
  end
.,.,

 # reduce 2 omitted

 # reduce 3 omitted

 # reduce 4 omitted

 # reduce 5 omitted

 # reduce 6 omitted

 # reduce 7 omitted

 # reduce 8 omitted

 # reduce 9 omitted

 # reduce 10 omitted

module_eval <<'.,.,', 'xabsl_parser.y.rb', 99
  def _reduce_11( val, _values, result )
return @stb.include(val)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 105
  def _reduce_12( val, _values, result )
@stb.namespace_early(_values)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 108
  def _reduce_13( val, _values, result )
return @stb.namespace(val)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 114
  def _reduce_14( val, _values, result )
 return val[0] + [val[1]]
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 118
  def _reduce_15( val, _values, result )
 return val[0] + [val[1]]
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 122
  def _reduce_16( val, _values, result )
 return val[0] + [val[1]]
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 126
  def _reduce_17( val, _values, result )
 return val[0] + [val[1]]
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 128
  def _reduce_18( val, _values, result )
 return []
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 135
  def _reduce_19( val, _values, result )
@stb.behavior_declaration_early(_values)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 138
  def _reduce_20( val, _values, result )
 return @stb.behavior_declaration(val)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 144
  def _reduce_21( val, _values, result )
@stb.symbol_declaration_early(_values)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 147
  def _reduce_22( val, _values, result )
return @stb.symbol_declaration(val)
   result
  end
.,.,

 # reduce 23 omitted

 # reduce 24 omitted

 # reduce 25 omitted

 # reduce 26 omitted

module_eval <<'.,.,', 'xabsl_parser.y.rb', 166
  def _reduce_27( val, _values, result )
 return @stb.enum_symbol_declaration(val)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 172
  def _reduce_28( val, _values, result )
 return [val[0]] + val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 178
  def _reduce_29( val, _values, result )
 return val[0] + [val[2]]
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 180
  def _reduce_30( val, _values, result )
 return []
   result
  end
.,.,

 # reduce 31 omitted

 # reduce 32 omitted

 # reduce 33 omitted

 # reduce 34 omitted

module_eval <<'.,.,', 'xabsl_parser.y.rb', 197
  def _reduce_35( val, _values, result )
  return val[1]
   result
  end
.,.,

 # reduce 36 omitted

module_eval <<'.,.,', 'xabsl_parser.y.rb', 203
  def _reduce_37( val, _values, result )
return @stb.const(val)
   result
  end
.,.,

 # reduce 38 omitted

 # reduce 39 omitted

module_eval <<'.,.,', 'xabsl_parser.y.rb', 214
  def _reduce_40( val, _values, result )
return @stb.agent(val)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 220
  def _reduce_41( val, _values, result )
@stb.option_early(_values)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 225
  def _reduce_42( val, _values, result )
return @stb.option(val)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 232
  def _reduce_43( val, _values, result )
 return val[1]
   result
  end
.,.,

 # reduce 44 omitted

module_eval <<'.,.,', 'xabsl_parser.y.rb', 239
  def _reduce_45( val, _values, result )
 return [] + val[0] + [val[1]]
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 241
  def _reduce_46( val, _values, result )
 return []
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 246
  def _reduce_47( val, _values, result )
return @stb.parameter_declaration(val)
   result
  end
.,.,

 # reduce 48 omitted

 # reduce 49 omitted

 # reduce 50 omitted

 # reduce 51 omitted

module_eval <<'.,.,', 'xabsl_parser.y.rb', 262
  def _reduce_52( val, _values, result )
 return [val[0]] + val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 268
  def _reduce_53( val, _values, result )
 return [] + val[0] + [val[1]]
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 270
  def _reduce_54( val, _values, result )
 return []
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 274
  def _reduce_55( val, _values, result )
@stb.state_declaration_early(_values)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 280
  def _reduce_56( val, _values, result )
 return @stb.state_declaration(val)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 285
  def _reduce_57( val, _values, result )
 return val[0] + [val[1]]
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 289
  def _reduce_58( val, _values, result )
 return val[0] + [val[1]]
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 291
  def _reduce_59( val, _values, result )
 return []
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 295
  def _reduce_60( val, _values, result )
@stb.output_symbol_assignment_early(_values)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 297
  def _reduce_61( val, _values, result )
 return @stb.output_symbol_assignment(val)
   result
  end
.,.,

 # reduce 62 omitted

 # reduce 63 omitted

 # reduce 64 omitted

 # reduce 65 omitted

 # reduce 66 omitted

 # reduce 67 omitted

module_eval <<'.,.,', 'xabsl_parser.y.rb', 316
  def _reduce_68( val, _values, result )
@stb.subsequent_declaration_early(_values)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 318
  def _reduce_69( val, _values, result )
return @stb.subsequent_declaration(val)
   result
  end
.,.,

 # reduce 70 omitted

 # reduce 71 omitted

 # reduce 72 omitted

module_eval <<'.,.,', 'xabsl_parser.y.rb', 329
  def _reduce_73( val, _values, result )
return [val[0]] + val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 331
  def _reduce_74( val, _values, result )
return []
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 336
  def _reduce_75( val, _values, result )
return val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 338
  def _reduce_76( val, _values, result )
return []
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 343
  def _reduce_77( val, _values, result )
@stb.set_parameter_early(_values)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 345
  def _reduce_78( val, _values, result )
return @stb.set_parameter(val)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 350
  def _reduce_79( val, _values, result )
return [val[0]] + val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 352
  def _reduce_80( val, _values, result )
return []
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 357
  def _reduce_81( val, _values, result )
return val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 359
  def _reduce_82( val, _values, result )
return []
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 364
  def _reduce_83( val, _values, result )
@stb.with_parameter_early(_values)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 366
  def _reduce_84( val, _values, result )
return @stb.with_parameter(val)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 371
  def _reduce_85( val, _values, result )
return @stb.exp_unary(val)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 373
  def _reduce_86( val, _values, result )
@stb.exp_binary_early(_values)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 374
  def _reduce_87( val, _values, result )
return @stb.exp_binary(val)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 376
  def _reduce_88( val, _values, result )
@stb.exp_binary_early(_values)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 377
  def _reduce_89( val, _values, result )
return @stb.exp_binary(val)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 379
  def _reduce_90( val, _values, result )
@stb.exp_binary_early(_values)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 380
  def _reduce_91( val, _values, result )
return @stb.exp_binary(val)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 382
  def _reduce_92( val, _values, result )
@stb.exp_binary_early(_values)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 383
  def _reduce_93( val, _values, result )
return @stb.exp_binary(val)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 385
  def _reduce_94( val, _values, result )
@stb.exp_binary_early(_values)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 386
  def _reduce_95( val, _values, result )
return @stb.exp_binary(val)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 388
  def _reduce_96( val, _values, result )
@stb.exp_binary_early(_values)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 389
  def _reduce_97( val, _values, result )
return @stb.exp_binary(val)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 391
  def _reduce_98( val, _values, result )
@stb.exp_binary_early(_values)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 392
  def _reduce_99( val, _values, result )
return @stb.exp_binary(val)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 394
  def _reduce_100( val, _values, result )
@stb.exp_binary_early(_values)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 395
  def _reduce_101( val, _values, result )
return @stb.exp_binary(val)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 397
  def _reduce_102( val, _values, result )
@stb.exp_binary_early(_values)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 398
  def _reduce_103( val, _values, result )
return @stb.exp_binary(val)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 400
  def _reduce_104( val, _values, result )
@stb.exp_binary_early(_values)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 401
  def _reduce_105( val, _values, result )
return @stb.exp_binary(val)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 403
  def _reduce_106( val, _values, result )
@stb.exp_binary_early(_values)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 404
  def _reduce_107( val, _values, result )
return @stb.exp_binary(val)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 406
  def _reduce_108( val, _values, result )
@stb.exp_binary_early(_values)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 407
  def _reduce_109( val, _values, result )
return @stb.exp_binary(val)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 409
  def _reduce_110( val, _values, result )
@stb.exp_binary_early(_values)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 410
  def _reduce_111( val, _values, result )
return @stb.exp_binary(val)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 413
  def _reduce_112( val, _values, result )
return @stb.conditional_expression(val)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 416
  def _reduce_113( val, _values, result )
return val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 419
  def _reduce_114( val, _values, result )
return @stb.exp_unary(val)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 422
  def _reduce_115( val, _values, result )
return @stb.exp_number(val)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 425
  def _reduce_116( val, _values, result )
return @stb.exp_boolean(val)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 428
  def _reduce_117( val, _values, result )
return @stb.exp_boolean(val)
   result
  end
.,.,

 # reduce 118 omitted

module_eval <<'.,.,', 'xabsl_parser.y.rb', 433
  def _reduce_119( val, _values, result )
return @stb.exp_identifier(val)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 436
  def _reduce_120( val, _values, result )
return TOSXTag.new
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 439
  def _reduce_121( val, _values, result )
return TOOXTag.new
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 442
  def _reduce_122( val, _values, result )
return SORTSTag.new
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 449
  def _reduce_123( val, _values, result )
@stb.function_early(_values)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 451
  def _reduce_124( val, _values, result )
return @stb.function(val)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 459
  def _reduce_125( val, _values, result )
return [val[2], val[5]]
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 463
  def _reduce_126( val, _values, result )
return [val[2]]
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 467
  def _reduce_127( val, _values, result )
return [val[2]]
   result
  end
.,.,

 # reduce 128 omitted

module_eval <<'.,.,', 'xabsl_parser.y.rb', 474
  def _reduce_129( val, _values, result )
return @stb.common_action(val)
   result
  end
.,.,

 # reduce 130 omitted

module_eval <<'.,.,', 'xabsl_parser.y.rb', 480
  def _reduce_131( val, _values, result )
return @stb.common_decision_tree(val)
   result
  end
.,.,

 # reduce 132 omitted

module_eval <<'.,.,', 'xabsl_parser.y.rb', 488
  def _reduce_133( val, _values, result )
return val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 493
  def _reduce_134( val, _values, result )
return @stb.cdtree(val)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 498
  def _reduce_135( val, _values, result )
return @stb.cdtree_elseif_decision(val)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 500
  def _reduce_136( val, _values, result )
return nil
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 505
  def _reduce_137( val, _values, result )
return @stb.decision_tree(val)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 508
  def _reduce_138( val, _values, result )
return @stb.decision_tree(val)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 510
  def _reduce_139( val, _values, result )
return @stb.decision_tree(val)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 518
  def _reduce_140( val, _values, result )
return val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 521
  def _reduce_141( val, _values, result )
return [val[0]]
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 527
  def _reduce_142( val, _values, result )
return @stb.dtree(val)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 533
  def _reduce_143( val, _values, result )
return @stb.transition(val)
   result
  end
.,.,

module_eval <<'.,.,', 'xabsl_parser.y.rb', 536
  def _reduce_144( val, _values, result )
return @stb.transition(val)
   result
  end
.,.,

 def _reduce_none( val, _values, result )
  result
 end

  end   # class XabslParser

end   # module Translator
